// import { User } from 'src/app/models/user.model';

// export const UserTestData: User[] = [
//   {
//     id: 0,
//     firstName: 'Strickland',
//     middleName: 'Rocha',
//     lastName: 'Hardy',
//     email: 'sylviawong@accuprint.com',
//     phoneNumber: '(912) 478-2222',
//     userDetails: {
//       ucn: "8394462006",
//       address: 'Guinea-Bissau',
//       country: 'Ethiopia',
//       city: 'Gordon',
//       cityPostCode: "9605",
//       street: 'Henderson Walk',
//     },
//   },
//   {
//     id: 1,
//     firstName: 'Vera',
//     middleName: 'Dorsey',
//     lastName: 'Lewis',
//     email: 'lambertroy@comveyer.com',
//     phoneNumber: '(900) 414-2928',
//     userDetails: {
//       ucn: "8615343764",
//       address: 'French Guiana',
//       country: 'South Africa',
//       city: 'Abiquiu',
//       cityPostCode: "9394",
//       street: 'Rutland Road',
//     },
//   },
//   {
//     id: 2,
//     firstName: 'Jayne',
//     middleName: 'Porter',
//     lastName: 'Perez',
//     email: 'forbesross@interloo.com',
//     phoneNumber: '(921) 584-2633',
//     userDetails: {
//       ucn: "8954643613",
//       address: 'Cyprus',
//       country: 'Sweden',
//       city: 'Fontanelle',
//       cityPostCode: "8205",
//       street: 'Battery Avenue',
//     },
//   },
//   {
//     id: 3,
//     firstName: 'Bobbi',
//     middleName: 'Barnes',
//     lastName: 'Wade',
//     email: 'wongwoods@beadzza.com',
//     phoneNumber: '(868) 534-3049',
//     userDetails: {
//       ucn: "8015112599",
//       address: 'Micronesia',
//       country: 'Cayman Islands',
//       city: 'Vaughn',
//       cityPostCode: "8995",
//       street: 'High Street',
//     },
//   },
//   {
//     id: 4,
//     firstName: 'Eddie',
//     middleName: 'Mathis',
//     lastName: 'Talley',
//     email: 'hannahrivers@elemantra.com',
//     phoneNumber: '(863) 563-3063',
//     userDetails: {
//       ucn: "8995833746",
//       address: 'Portugal',
//       country: 'Gabon',
//       city: 'Takilma',
//       cityPostCode: "8415",
//       street: 'Woodrow Court',
//     },
//   },
//   {
//     id: 5,
//     firstName: 'Danielle',
//     middleName: 'Klein',
//     lastName: 'Velazquez',
//     email: 'rayjacobs@quiltigen.com',
//     phoneNumber: '(865) 492-3394',
//     userDetails: {
//       ucn: "9645763946",
//       address: 'Brunei Darussalam',
//       country: 'Samoa',
//       city: 'Barclay',
//       cityPostCode: "8374",
//       street: 'Eastern Parkway',
//     },
//   },
//   {
//     id: 6,
//     firstName: 'Bowers',
//     middleName: 'Snider',
//     lastName: 'Whitley',
//     email: 'tommietrujillo@speedbolt.com',
//     phoneNumber: '(925) 402-3476',
//     userDetails: {
//       ucn: "8404852585",
//       address: 'Netherlands Antilles',
//       country: 'Benin',
//       city: 'Spelter',
//       cityPostCode: "9655",
//       street: 'Hunterfly Place',
//     },
//   },
//   {
//     id: 7,
//     firstName: 'Kay',
//     middleName: 'Lynn',
//     lastName: 'Alvarado',
//     email: 'colettekeith@schoolio.com',
//     phoneNumber: '(979) 438-3651',
//     userDetails: {
//       ucn: "9704993249",
//       address: 'Costa Rica',
//       country: 'Trinidad and Tobago',
//       city: 'Joppa',
//       cityPostCode: "8965",
//       street: 'Lott Avenue',
//     },
//   },
//   {
//     id: 8,
//     firstName: 'Angel',
//     middleName: 'Brooks',
//     lastName: 'Rogers',
//     email: 'mathewsbranch@geekus.com',
//     phoneNumber: '(833) 432-3218',
//     userDetails: {
//       ucn: "9614592022",
//       address: 'Egypt',
//       country: 'Kiribati',
//       city: 'Noblestown',
//       cityPostCode: "8205",
//       street: 'Lewis Place',
//     },
//   },
//   {
//     id: 9,
//     firstName: 'Maura',
//     middleName: 'Bowman',
//     lastName: 'Carlson',
//     email: 'petrahouse@dyno.com',
//     phoneNumber: '(848) 586-2831',
//     userDetails: {
//       ucn: "8924172481",
//       address: 'Gibraltar',
//       country: 'Saint Kitts and Nevis',
//       city: 'Englevale',
//       cityPostCode: "8894",
//       street: 'Schenck Place',
//     },
//   },
//   {
//     id: 10,
//     firstName: 'Joyner',
//     middleName: 'Meyer',
//     lastName: 'William',
//     email: 'hahnchambers@eternis.com',
//     phoneNumber: '(938) 419-3986',
//     userDetails: {
//       ucn: "9705802590",
//       address: 'Djibouti',
//       country: 'Israel',
//       city: 'Escondida',
//       cityPostCode: "9475",
//       street: 'Homecrest Avenue',
//     },
//   },
//   {
//     id: 11,
//     firstName: 'Aguilar',
//     middleName: 'Ortega',
//     lastName: 'Roberts',
//     email: 'cooleystokes@izzby.com',
//     phoneNumber: '(909) 432-2981',
//     userDetails: {
//       ucn: "9915313918",
//       address: 'Mauritania',
//       country: 'Niger',
//       city: 'Hayden',
//       cityPostCode: "8334",
//       street: 'Lamont Court',
//     },
//   },
//   {
//     id: 12,
//     firstName: 'Dale',
//     middleName: 'Rowe',
//     lastName: 'Delacruz',
//     email: 'revagriffin@namebox.com',
//     phoneNumber: '(968) 453-2155',
//     userDetails: {
//       ucn: "8445742321",
//       address: "Cote D'Ivoire (Ivory Coast)",
//       country: 'Korea (North)',
//       city: 'Buxton',
//       cityPostCode: "8154",
//       street: 'Portal Street',
//     },
//   },
//   {
//     id: 13,
//     firstName: 'Marsh',
//     middleName: 'Gallagher',
//     lastName: 'Conway',
//     email: 'princealbert@assistia.com',
//     phoneNumber: '(818) 538-3170',
//     userDetails: {
//       ucn: "9074833671",
//       address: 'Ukraine',
//       country: 'Pakistan',
//       city: 'Keller',
//       cityPostCode: "9125",
//       street: 'Railroad Avenue',
//     },
//   },
//   {
//     id: 14,
//     firstName: 'Case',
//     middleName: 'Fernandez',
//     lastName: 'Vazquez',
//     email: 'millieprince@zentia.com',
//     phoneNumber: '(816) 516-3880',
//     userDetails: {
//       ucn: "8114092270",
//       address: 'Mayotte',
//       country: 'Sri Lanka',
//       city: 'Fairmount',
//       cityPostCode: "9715",
//       street: 'Schenectady Avenue',
//     },
//   },
//   {
//     id: 15,
//     firstName: 'Jackson',
//     middleName: 'Battle',
//     lastName: 'Dodson',
//     email: 'alfordpierce@portaline.com',
//     phoneNumber: '(939) 480-3453',
//     userDetails: {
//       ucn: "8504352084",
//       address: 'Thailand',
//       country: 'Maldives',
//       city: 'Singer',
//       cityPostCode: "9615",
//       street: 'Green Street',
//     },
//   },
// ];
